/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Fotter: typeof import('./src/components/Home/content/Fotter.vue')['default']
    HeaderNav: typeof import('./src/components/Home/content/HeaderNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home/index.vue')['default']
    HomeFooter: typeof import('./src/components/Home/content/HomeFooter.vue')['default']
    HomeHeader: typeof import('./src/components/Home/content/HomeHeader.vue')['default']
    HomeMain: typeof import('./src/components/Home/content/HomeMain.vue')['default']
    HomeNav: typeof import('./src/components/Home/content/HomeNav.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    LoginForm: typeof import('./src/components/Login/content/LoginForm.vue')['default']
    Navigation: typeof import('./src/components/Home/Layout/Navigation.vue')['default']
    PageLayout: typeof import('./src/components/Home/content/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterNav: typeof import('./src/components/Home/content/RouterNav.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SettingCenter: typeof import('./src/components/SettingCenter/index.vue')['default']
    SideBar: typeof import('./src/components/Home/content/SideBar.vue')['default']
    SideMenu: typeof import('./src/components/Home/content/SideMenu.vue')['default']
    Signin: typeof import('./src/components/Login/content/Signin.vue')['default']
    SigninForm: typeof import('./src/components/Login/content/SigninForm.vue')['default']
    SignupForm: typeof import('./src/components/Login/content/SignupForm.vue')['default']
    UserCenter: typeof import('./src/components/UserCenter/index.vue')['default']
  }
}
